### ISSUE TITLE
Support think times

### ISSUE THREAD

**Issue by mrichman** [mrichman/hargo#1]
Think times are used to simulate human behavior that causes people to wait between interactions with a Web site. Think times occur between requests in a Web performance test and between test iterations in a load test scenario. Using think times in a load test can be useful in creating more accurate load simulations.

Without think times, URLs are requested as quickly as possible.

**Comment by marcelmiguel** [comment]
+1
Even better for me, is to wait the exact time between calls as saved on the HAR file.

**Comment by mrichman** [comment]
@marcelmiguel Thanks for your input. Would you want think times (as saved in the HAR file) to be the default behavior, or an optional flag?

**Comment by marcelmiguel** [comment]
For me, default behaviour.
Thank fou for this great utility.
