### ISSUE TITLE
JSON tags messed up

### ISSUE THREAD

**Issue by mediocregopher** [mrichman/hargo#2]
Hi there! Just wanted to provide some feedback on some ways you could improve the json struct tags in hargo:

1) Right now you have a lot of fields like this:

```
Text string `json:"omitempty"`
```

What you're doing here is telling the json unmarshaler to look for the field `omitempty` in the json object, which isn't what you want. What I think you're trying to do is this:

```
Text string `json:",omitempty"`
```

Which tells it to look for `text` or `Text` in the json object, and omit the field when marshaling if it's empty.

2) It would break backwards compat, but setting the field names to be their lower case versions, like so:

```
Text string `json:"text,omitempty"`
```

would make it so that once you have a Har unmarshaled into your program you can unmarshal it again into the same form, rather than a new set of objects with different field names that can't be used by chrome or any other tool which is reading in Har as json objects.

I'm going to make a fork of your project and implement these changes, if you like I can PR them back up. Thanks for all the work on it so far, it's been really helpful!

**Comment by mrichman** [comment]
Wow, thanks for the feedback! I wasn't aware anyone was actually using this, so I'm flattered. If you're finding it useful, please send me a PR and I'll gladly merge. This was my first real attempt at a Go package that other could use, so I hope I'm doing things idiomatically. I'm very open to constructive criticism. - Mark

**Comment by mediocregopher** [comment]
PR sent in. I honestly haven't used the cli tool you made, but just you having put together all the types has been extremely helpful, so thank you for that :) One other piece of feedback I'd give is that there's quite a few places where you're taking in `*bufio.Reader` instances where you could be just taking in an `io.Reader`. It's usually better to take in the highest level of abstracted interface as is possible, because it'll give your user more freedom and make composing your stuff into their stuff easier. Not a big deal, but that's the other big thing that stuck out to me when looking at the package.

Again, thanks for putting all the work in to writing the package, it's been very helpful for me :)
