### ISSUE TITLE
where is it saving , there is nothing in my gopath?

### ISSUE THREAD

**Issue by ishandutta2007** [mrichman/hargo#21]
$ `go get github.com/mrichman/hargo`
$ `cd $GOPATH/src/github.com/mrichman/hargo`

> -bash: cd: /Users/ishandutta2007/gopath/src/github.com/mrichman/hargo: No such file or directory

$ `echo $GOPATH`
> /Users/ishandutta2007/gopath

$ `ls /Users/ishandutta2007/gopath`
$

**Comment by ishandutta2007** [comment]
More details on my go installation paths:

$`brew info go`

> go: stable 1.13.4 (bottled), HEAD
> Open source programming language to build simple/reliable/efficient software
> https://golang.org
> /usr/local/Cellar/go/1.7.4 (6,438 files, 250.7MB)
>   Poured from bottle on 2016-12-07 at 22:22:21
> /usr/local/Cellar/go/1.10.2 (8,161 files, 336.7MB) *
>   Poured from bottle on 2018-06-02 at 20:09:15
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/go.rb
> ==> Requirements
> Required: macOS >= 10.11 ✔
> ==> Options
> --HEAD
> 	Install HEAD version
> ==> Analytics
> install: 105,558 (30 days), 345,396 (90 days), 1,267,963 (365 days)
> install_on_request: 82,574 (30 days), 273,482 (90 days), 971,167 (365 days)
> build_error: 0 (30 days)
> 

$ `which go`
> /usr/local/bin/go

**Comment by mrichman** [comment]
Did you find it?

**Comment by ishandutta2007** [comment]
Well long time, I guess I had given up working on it and used some other tool back then. Anywways would be great to document such basic stuff for beginners (esp ones with less patience like me :P)

**Comment by mrichman** [comment]
Sorry about that. I never updated the README after Go 1.8 where `$GOPATH` was set automatically to `$HOME/go`.

Added this to README:

`export GOPATH=$HOME/go`
