### ISSUE TITLE
tag `0.1.2` is inconsistent with prior tags, should be `v0.1.2`

### ISSUE THREAD

**Issue by agraves** [mrichman/hargo#22]
Hey there -- was trying this package out and went down a rabbit hole trying to figure out why I couldn't get the latest version. After some detective work I noticed that your latest version is tagged `0.1.2` (no v) whereas the previous version was `v0.1.1`.

I suspect this is causing people to not get `0.1.1` when they pull.

**Comment by mrichman** [comment]
Thanks for pointing this out. See if this works for you now - I created a new release for `v0.1.2` off master: https://github.com/mrichman/hargo/tree/v0.1.2

**Comment by mrichman** [comment]
Closing — no reply.
