### ISSUE TITLE
Having trouble with the go get command

### ISSUE THREAD

**Issue by Bp3289** [mrichman/hargo#26]
When I run `go get github.com/mrichman/hargo` I receive this error "can't load package: package github.com/mrichman/hargo: no Go files in /Users/billy/go/src/github.com/mrichman/hargo"

Can someone explain what I'm doing wrong?

Thanks!

**Comment by mrichman** [comment]
What version of Go are you using?

I'm on 1.16.3:

```sh
$ go version
go version go1.16.3 darwin/amd64
```
And when I do `go get github.com/mrichman/hargo` I get:

```sh
go get github.com/mrichman/hargo
go: downloading github.com/mrichman/hargo v0.1.2
go: downloading github.com/influxdata/influxdb1-client v0.0.0-20190809212627-fc22c7df067e
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: downloading golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: downloading golang.org/x/text v0.3.0
```

**Comment by Bp3289** [comment]
go version go1.10.2 darwin/amd64. In the docs it says I need to have 1.9 or higher

**Comment by mrichman** [comment]
Sorry about that. I only maintain 2 major versions back. Try Go >= 1.14 though 1.12 would probably work too.

**Comment by Bp3289** [comment]
Updated Go and it worked! Thanks for the quick response! Closing issue.

**Comment by mrichman** [comment]
Glad to hear it! What are you using my tool for? I'm always eager to hear, as I didn't really expect it to become popular. It really just started as a hobby project to learn Go.

**Comment by Bp3289** [comment]
I found when googling ways to Load test .har files. It's the second link! While I have you here, I ran into another issue. When I try to run `go run cmd/hargo/hargo.go validate test/golang.org.har` I'm getting this message: "stat cmd/hargo/hargo.go: no such file or directory".

I'm following the docs, so I already did steps:
go get github.com/mrichman/hargo
export GOPATH=$HOME/go
cd $GOPATH/src/github.com/mrichman/hargo

**Comment by mrichman** [comment]
It looks like they changed the behavior of `go get` in newer versions of Go. I'll fix the doc, but what you should do is just clone the repo, and then your command will work.

For example, I clone into `$HOME/github.com/mrichman`:

```sh
mkdir -p ~/github.com/mrichman
cd ~/github.com/mrichman
git clone https://github.com/mrichman/hargo
cd hargo
go run cmd/hargo/hargo.go validate test/golang.org.har

INFO[0000] validate .har file: test/golang.org.har
Valid HAR file! 😊
```

See if that works for you, and I'll update the doc accordingly.

**Comment by Bp3289** [comment]
Works like a charm! Thank you so much for the quick responses. This is a really cool tool, thanks for making it!
