### ISSUE TITLE
Dependency changed

### ISSUE THREAD

**Issue by csutorasr** [mrichman/hargo#4]
I found the following error:

```
cmd\hargo\hargo.go:13:2: cannot find package "github.com/urfave/cli" in any of:
        C:\Go\src\github.com\urfave\cli (from $GOROOT)
        C:\Users\Csuto\go\src\github.com\urfave\cli (from $GOPATH)
```

I found out that happened as the cli has changed its repository (or whatever it called in GO, I haven't ever used it before).

The new repository is: `gopkg.in/urfave/cli.v1`. It should be changed in `hargo.go` import part, and in the dependecies.

Workaround:
Change it in hargo.go and run `go get gopkg.in/urfave/cli.v1`.

**Comment by mrichman** [comment]
Want to send me a PR?

**Comment by csutorasr** [comment]
I tried but I get error during `glide get gopkg.in/urfave/cli.v1`.

**Comment by matthiaz** [comment]
have you tried installing go 1.8 and running the make install again? That worked for me

**Comment by mrichman** [comment]
I just commit a change, pinning `gopkg.in/urfave/cli.v1`
